/**
 * Fetch each BBS post's detail HTML, extract title/author/date/body, and
 * save as static data in src/data/boardPostDetails.ts.
 *
 * Usage: npx tsx scripts/fetch-bbs-details.ts
 */
import fs from 'fs';
import { eventPosts, reviewPosts } from '../src/data/boardPosts';

const BASE = 'https://hyedu.kr';

type Detail = {
  id: string;
  title: string;
  author: string;
  date: string;
  body: string;
};

function extract(html: string): Omit<Detail, 'id'> {
  const titleMatch = html.match(/<div class="page-header">\s*<h4>([\s\S]*?)<\/h4>/);
  const authorMatch = html.match(/<strong>작성자<\/strong>\s*([^<]+?)\s*<\/span>/);
  const timeMatch = html.match(/<strong>시간<\/strong>\s*([^<]+?)\s*<\/span>/);

  // Body: everything inside the content container
  const bodyMatch = html.match(
    /<div class="col-xs-12" style="padding:100px 20px;">[^\n]*?<!--내용 Sample-->([\s\S]*?)(?=<div class="col-xs-12 dh-line">)/
  );
  let body = bodyMatch ? bodyMatch[1].trim() : '';
  // Trim trailing closing div
  body = body.replace(/<\/div>\s*$/, '').trim();

  // Rewrite relative image srcs to absolute
  body = body.replace(/src=(["'])\/(?!\/)/g, `src=$1${BASE}/`);
  // Strip inline styles that lock layout (color/font-family/font-size)
  body = body.replace(/\s(color|font-family|font-size):[^;"]+;?/g, '');
  // Drop now-empty style="" attrs and orphan ones
  body = body.replace(/\sstyle=(["'])\s*\1/g, '');
  body = body.replace(/\sstyle=(["'])\s*;+\s*\1/g, '');

  return {
    title: titleMatch ? titleMatch[1].replace(/<[^>]+>/g, '').replace(/&amp;/g, '&').replace(/&nbsp;/g, ' ').trim() : '',
    author: authorMatch ? authorMatch[1].trim() : '한양미래연구소',
    date: timeMatch ? timeMatch[1].trim() : '',
    body,
  };
}

async function fetchDetail(bbsNo: number, dataNo: string): Promise<Detail> {
  const url = `${BASE}/bbs/bbs/view.php?bbs_no=${bbsNo}&data_no=${dataNo}`;
  const res = await fetch(url, {
    headers: { 'User-Agent': 'HyeduRebuildBot/1.0' },
  });
  if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
  const html = await res.text();
  return { id: dataNo, ...extract(html) };
}

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

async function main() {
  const results: { events: Detail[]; reviews: Detail[] } = { events: [], reviews: [] };

  console.error(`Fetching ${eventPosts.length} events...`);
  for (const p of eventPosts) {
    try {
      const d = await fetchDetail(13, p.id);
      results.events.push(d);
      console.error(`  [OK] ${p.id} ${d.title.slice(0, 40)}`);
    } catch (e) {
      console.error(`  [FAIL] ${p.id}: ${e}`);
    }
    await sleep(300);
  }

  console.error(`\nFetching ${reviewPosts.length} reviews...`);
  for (const p of reviewPosts) {
    try {
      const d = await fetchDetail(10, p.id);
      results.reviews.push(d);
      console.error(`  [OK] ${p.id} ${d.title.slice(0, 40)}`);
    } catch (e) {
      console.error(`  [FAIL] ${p.id}: ${e}`);
    }
    await sleep(300);
  }

  // Generate TS file
  const toEntry = (d: Detail) =>
    `  ${JSON.stringify(d.id)}: {\n    title: ${JSON.stringify(d.title)},\n    author: ${JSON.stringify(d.author)},\n    date: ${JSON.stringify(d.date)},\n    body: ${JSON.stringify(d.body)},\n  }`;

  const ts =
    `/* Auto-generated by scripts/fetch-bbs-details.ts — do not edit by hand. */\n\n` +
    `export interface BoardPostDetail {\n  title: string;\n  author: string;\n  date: string;\n  body: string;\n}\n\n` +
    `export const eventDetails: Record<string, BoardPostDetail> = {\n` +
    results.events.map(toEntry).join(',\n') +
    `,\n};\n\n` +
    `export const reviewDetails: Record<string, BoardPostDetail> = {\n` +
    results.reviews.map(toEntry).join(',\n') +
    `,\n};\n`;

  fs.writeFileSync('src/data/boardPostDetails.ts', ts);
  console.error(`\nWrote src/data/boardPostDetails.ts (${ts.length} chars)`);
  console.error(`events: ${results.events.length}/${eventPosts.length}, reviews: ${results.reviews.length}/${reviewPosts.length}`);
}

main().catch((e) => {
  console.error('Fatal:', e);
  process.exit(1);
});
